site_title: ProgNovel
contact: prognovel@gmail.com
payment_pointer: $wallet.example.com/test
backend_api: https://api.prognovel.workers.dev

### PUBLISHED BOOKS ###
# you can left out a book folder if you're not ready to publish a certain book
novels:
  - yashura-legacy
  - mock-novel

### WEBMONETIZATION REVSHARE OPTIONS ###
# can point to multiple payment pointers with rev share using webfunding syntax
payment_pointers_site_global:
  - platform: 10%

rev_share_contribution_per_chapter:
  author: 5
  translator: 4
  editor: 3
  proofreader: 2
