on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  publish:
    if: github.actor!= 'depbot'
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm link
      - run: prognovel build
      - run: prognovel publish