on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true &&
      github.actor!= 'depbot'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm link
      - run: prognovel build
      - run: prognovel publish
